services:
  football_bot:  # NAME
    build:
      context: .
    container_name: football_bot # NAME
    stop_signal: SIGKILL
    ports:
      - 5012:5012 # PORTS
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ../football_bot:/telegram_bot
    environment:
      - LOCAL_ENV=prod

  postgres:
    image: postgres
    container_name: football_postgres # NAME
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
