services:
  football_bot:  # NAME
    build:
      context: .
    container_name: football_bot # NAME
    stop_signal: SIGKILL
    ports:
      - 5003:5003 # PORTS
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ../football_bot:/telegram_bot
    environment:
      - LOCAL_ENV=local
    develop:
      watch:
        - action: sync
          path: ./football_bot
          target: /telegram_bot
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt

  postgres:
    image: postgres
    container_name: football_postgres # NAME
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
