services:
  BOT_NAME:  # NAME
    build:
      context: .
    container_name: BOT_NAME # NAME
    stop_signal: SIGKILL
    ports:
      - 5003:5003 # PORTS
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ./report_bot:/telegram_bot
    environment:
      - LOCAL_ENV=prod

  postgres:
    image: postgres
    container_name: BOT_postgres # NAME
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
